version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  ProjectVersion: build$(APPVEYOR_BUILD_VERSION)
  matrix:
  - PYTHON: C:\PYTHON36
install:
  - ps: 'if(Test-Path env:APPVEYOR_REPO_TAG_NAME) {$env:ProjectVersion=$env:APPVEYOR_REPO_TAG_NAME}'
  - '%PYTHON%\python.exe --version'
  - '%PYTHON%\Scripts\pip install pyinstaller'
  - '%PYTHON%\Scripts\pip install markdown'
  - '%PYTHON%\python.exe -m markdown README.md > README.html'
  - '%PYTHON%\Scripts\pyinstaller bundle\OoTRandomizer.spec'
  - 'mkdir dist\OoTRandomizer\ext'
  - 'move dist\OoTRandomizer\*.pyd dist\OoTRandomizer\ext'
  - 'move dist\OoTRandomizer\tcl*.dll dist\OoTRandomizer\ext'
  - 'move dist\OoTRandomizer\tk*.dll dist\OoTRandomizer\ext'
  - ps: '$env:OoTR_Version= &"$env:PYTHON\python.exe" -c "import Main; import re; print(re.match(''[0-9]+\\.[0-9]+\\.[0-9]+'',Main.__version__).group(0))"'
  - '"%WIX%\bin\heat.exe" dir "dist\OoTRandomizer" -sfrag -srd -suid -dr INSTALLDIR -cg OoTRFiles -ag -template fragment -t bundle\components.xslt -out build\components.wxs'
  - '"%WIX%\bin\candle.exe" -out build\ bundle\*.wxs build\*.wxs'
  - '"%WIX%\bin\light.exe" -ext WixUIExtension build\*.wixobj -o dist\OoTRandomizer-Installer-%ProjectVersion%-win32.msi -b dist\OoTRandomizer'
build: off
artifacts:
- path: dist/OoTRandomizer*.msi
  name: OoTRandomizer-Installer-$(ProjectVersion)-win32.msi
- path: dist/OoTRandomizer/
  name: OoTRandomizer-Raw-$(ProjectVersion)-win32.zip
